version: 2

aliases:
  - &test-base
    working_directory: /tmp/drafter
    environment:
      CXXFLAGS: '-Werror -Wno-error=unused-function'

    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Build
          command: |
            ./configure
            make -j4
      - run:
          name: Test
          command: make test -j4

  - &test-clang-base
    <<: *test-base
    environment:
      CXXFLAGS: '-Werror -Wno-error=unused-function -Wno-error=missing-braces'

  - &tag-filter
    filters:
      tags:
        only: /^v.*/

  - &update
    run:
      name: Update
      command: "apt-get update"

  - &update-backports
    run:
      name: "Add stretch-backports && Update"
      command: |
          echo "deb http://ftp.debian.org/debian stretch main" >> /etc/apt/sources.list
          echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
          apt-get update

  - &install-ruby
    run:
      name: Install Ruby
      command: 'apt-get install -y ruby ruby-dev'

  - &install-ruby-backports
    run:
      name: Install Ruby from stretch-backports
      command: |
          apt-get -t stretch-backports install -y --no-install-recommends ruby-build
          ruby-build --definitions
          ruby-build 2.3.4

  - &install-cmake
    run:
      name: Install CMake
      command: 'apt-get install -y cmake'

  - &install-cmake-backports
    run:
      name: Install CMake from stretch-backports
      command: 'apt-get -t stretch-backports install -y --no-install-recommends cmake'

  - &install-cmake-homebrew
    run:
      name: Install CMake
      command: 'brew install cmake'

  - &update-submodules
    run:
      name: Update submodules
      command: 'git submodule update --init --recursive'

  - &install-bundle
    run:
      name: Install integration test dependencies
      command: |
        gem uninstall bundler
        gem install bundler -v 1.10.3
        bundle install --path vendor/bundle

  - &install-valgrind
    run:
      name: Install valgrind
      command: "apt-get install -y valgrind"

  - &build-unix-release
    run:
      name: Build and test
      command: ctest -j4 -S cmake/unix.cmake -DCTEST_BUILD_TYPE=Release -DCTEST_BUILD_NAME="$(c++ --version | head -n1)"

  - &build-unix-debug
    run:
      name: Build and test
      command: ctest -j4 -S cmake/unix.cmake -DCTEST_BUILD_TYPE=Debug -DCTEST_BUILD_NAME="$(c++ --version | head -n1)"

  - &test-unix-release-backports
    working_directory: /tmp/drafter
    environment:
    steps:
      - <<: *update-backports
      - <<: *install-cmake-backports
      - checkout
      - <<: *update-submodules
      - <<: *install-ruby
      - <<: *install-bundle
      - <<: *build-unix-release

  - &test-unix-debug-backports
    working_directory: /tmp/drafter
    environment:
    steps:
      - <<: *update-backports
      - <<: *install-cmake-backports
      - checkout
      - <<: *update-submodules
      - <<: *install-ruby
      - <<: *install-bundle
      - <<: *build-unix-debug

  - &test-unix-release
    working_directory: /tmp/drafter
    environment:
    steps:
      - <<: *update
      - <<: *install-cmake
      - checkout
      - <<: *update-submodules
      - <<: *install-ruby
      - <<: *install-bundle
      - <<: *build-unix-release

  - &test-unix-debug
    working_directory: /tmp/drafter
    environment:
    steps:
      - <<: *update
      - <<: *install-cmake
      - checkout
      - <<: *update-submodules
      - <<: *install-ruby
      - <<: *install-bundle
      - <<: *build-unix-debug

  - &test-xcode-debug
    working_directory: /tmp/drafter
    environment:
    steps:
      - <<: *install-cmake-homebrew
      - checkout
      - <<: *update-submodules
      - run:
          name: Install integration test dependencies
          command: sudo gem install bundler && bundle install --path vendor/bundle
      - <<: *build-unix-debug

  - &test-xcode-release
    working_directory: /tmp/drafter
    environment:
    steps:
      - <<: *install-cmake-homebrew
      - checkout
      - <<: *update-submodules
      - run:
          name: Install integration test dependencies
          command: sudo gem install bundler && bundle install --path vendor/bundle
      - <<: *build-unix-release

workflows:
  version: 2

  drafter:
    jobs:
      - lint
      - test-gyp: *tag-filter
      - test-integration: *tag-filter
      - test-valgrind: *tag-filter
      - test-gcc5-release: *tag-filter
      - test-gcc5-debug: *tag-filter
      - test-gcc8-release: *tag-filter
      - test-gcc8-debug: *tag-filter
      - test-clang4-release: *tag-filter
      - test-clang4-debug: *tag-filter
      - test-clang6-release: *tag-filter
      - test-clang6-debug: *tag-filter
      - test-xcode9-release: *tag-filter
      - test-xcode9-debug: *tag-filter
      - release:
          requires:
            - test-gyp
            - test-integration
            - test-valgrind
            - test-gcc5-release
            - test-gcc5-debug
            - test-gcc8-release
            - test-gcc8-debug
            - test-clang4-release
            - test-clang4-debug
            - test-clang6-release
            - test-clang6-debug
            - test-xcode9-release
            - test-xcode9-debug
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  lint:
    docker:
      - image: apiaryio/clang:5

    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./tools/clang-format-check.sh

  test-gyp:
    <<: *test-base
    docker:
      - image: gcc:5.4

  test-gcc5-release:
    <<: *test-unix-release-backports
    docker:
      - image: gcc:5

  test-gcc5-debug:
    <<: *test-unix-debug-backports
    docker:
      - image: gcc:5

  test-gcc8-release:
    <<: *test-unix-release
    docker:
      - image: gcc:7

  test-gcc8-debug:
    <<: *test-unix-debug
    docker:
      - image: gcc:7

  test-clang4-release:
    <<: *test-unix-release-backports
    docker:
      - image: apiaryio/clang:4

  test-clang4-debug:
    <<: *test-unix-debug-backports
    docker:
      - image: apiaryio/clang:4

  test-clang6-release:
    <<: *test-unix-release
    docker:
      - image: apiaryio/clang:6

  test-clang6-debug:
    <<: *test-unix-debug
    docker:
      - image: apiaryio/clang:6

  test-xcode9-debug:
    <<: *test-xcode-debug
    macos:
      xcode: "9.4.0"

  test-xcode9-release:
    <<: *test-xcode-release
    macos:
      xcode: "9.4.0"

  test-integration:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: /tmp/drafter

    steps:
      - checkout
      - run: git submodule update --init --recursive

      - run:
          name: Build
          command: ./configure && make -j4

      - run:
          name: Integration Test
          command: bundle install && bundle exec cucumber

  test-valgrind:
    <<: *test-base
    docker:
      - image: gcc:7

    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: apt-get update && apt-get install -y valgrind

      - run:
          name: Build
          command: |
            ./configure
            make -j4
            make test -j4

      - run:
          name: Memory Test
          command: |
            mkdir artifacts
            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --error-exitcode=1 ./bin/test-libdrafter 2> artifacts/memcheck.log
            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --error-exitcode=1 ./bin/test-capi 2> artifacts/memcheck-capi.log

      - store_artifacts:
          path: artifacts

  release:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: /tmp/drafter

    steps:
      - checkout
      - <<: *update-submodules
      - run: ./tools/release.sh

